CREATE DATABASE IF NOT EXISTS BD_SENSORES;
USE BD_SENSORES;

CREATE TABLE IF NOT EXISTS SENSORES(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(200) NOT NULL,
    status BOOLEAN default true,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS MEDIDAS_SENSORES(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    dado VARCHAR(200) NOT NULL,
    unidade_medida VARCHAR(200) NOT NULL,
    data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    sensor_id INTEGER NOT NULL,
    FOREIGN KEY (sensor_id) REFERENCES SENSORES(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO SENSORES (nome, status )
VALUES ("DHT11",1);

INSERT INTO SENSORES (nome, status )
VALUES ("HC-SR04",1);

INSERT INTO SENSORES (nome, status )
VALUES ("RFID-RC522",1);

INSERT INTO SENSORES (nome, status )
VALUES ("MQ-135",1);

INSERT INTO MEDIDAS_SENSORES (dado, unidade_medida, data, sensor_id)
VALUES
("23.5","ºC", NOW(), 1), -- TEMPERATURA - DHT11
("50","%", NOW(), 1), -- UMIDADE - DHT11
("50","cm", NOW(), 2), -- DISTÂNCIA - HC-SR04
("1300","ppm", NOW(), 4); -- GÁS - MQ-135
